name: 腾讯00700.HK 盘中5分钟AI盯盘
on:
  schedule:
    # UTC时间 北京时间-8小时
    - cron: '*/5 1-4 * * 1-5'
    - cron: '*/5 5-8 * * 1-5'
    - cron: '0 9 * * 1-5'
  workflow_dispatch:

jobs:
  run_stock_watch:
    runs-on: ubuntu-latest
    env:
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      SERVER_SENDKEY: ${{ secrets.SERVER_SENDKEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - run: python3 stock_main.py
